// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_NTP_CLIENT_NTP_CLIENT_CORE_HPP_INCLUDED
#define TIME_SHIELD_HEADER_NTP_CLIENT_NTP_CLIENT_CORE_HPP_INCLUDED

#include <time_shield/ntp/detail/ntp_client_core.hpp>

#endif // TIME_SHIELD_HEADER_NTP_CLIENT_NTP_CLIENT_CORE_HPP_INCLUDED
