// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_NTP_CLIENT_UDP_TRANSPORT_WIN_HPP_INCLUDED
#define TIME_SHIELD_HEADER_NTP_CLIENT_UDP_TRANSPORT_WIN_HPP_INCLUDED

#include <time_shield/ntp/detail/udp_transport_win.hpp>

#endif // TIME_SHIELD_HEADER_NTP_CLIENT_UDP_TRANSPORT_WIN_HPP_INCLUDED
