// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_DETAIL_FAST_DATE_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_DETAIL_FAST_DATE_HPP_INCLUDED

#include <time_shield/conversions/detail/fast_date.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_DETAIL_FAST_DATE_HPP_INCLUDED
