// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_DETAIL_FLOOR_MATH_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_DETAIL_FLOOR_MATH_HPP_INCLUDED

#include <time_shield/conversions/detail/floor_math.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_DETAIL_FLOOR_MATH_HPP_INCLUDED
