// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_CONSTANTS_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_CONSTANTS_HPP_INCLUDED

#include <time_shield/core/constants.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_CONSTANTS_HPP_INCLUDED
