// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_ENUMS_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_ENUMS_HPP_INCLUDED

#include <time_shield/core/enums.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_ENUMS_HPP_INCLUDED
