// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_ISO_WEEK_CONVERSIONS_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_ISO_WEEK_CONVERSIONS_HPP_INCLUDED

#include <time_shield/conversions/iso_week_conversions.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_ISO_WEEK_CONVERSIONS_HPP_INCLUDED
