// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_MOONPHASE_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_MOONPHASE_HPP_INCLUDED

#include <time_shield/astronomy/MoonPhase.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_MOONPHASE_HPP_INCLUDED
