// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_NTP_CLIENT_POOL_RUNNER_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_NTP_CLIENT_POOL_RUNNER_HPP_INCLUDED

#include <time_shield/ntp/ntp_client_pool_runner.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_NTP_CLIENT_POOL_RUNNER_HPP_INCLUDED
