// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_CONVERSION_ALIASES_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_CONVERSION_ALIASES_HPP_INCLUDED

#include <time_shield/conversions/time_conversion_aliases.hpp>

#endif // TIME_SHIELD_HEADER_TIME_CONVERSION_ALIASES_HPP_INCLUDED
