// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_TIME_ZONE_OFFSET_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_TIME_ZONE_OFFSET_HPP_INCLUDED

#include <time_shield/conversions/time_zone_offset.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_TIME_ZONE_OFFSET_HPP_INCLUDED
