// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_TIME_STRUCT_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_TIME_STRUCT_HPP_INCLUDED

#include <time_shield/core/time_struct.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_TIME_STRUCT_HPP_INCLUDED
