// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIMERSCHEDULER_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIMERSCHEDULER_HPP_INCLUDED

#include <time_shield/timers/TimerScheduler.hpp>

#endif // TIME_SHIELD_HEADER_TIMERSCHEDULER_HPP_INCLUDED
