// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_VALIDATION_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_VALIDATION_HPP_INCLUDED

#include <time_shield/core/validation.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_VALIDATION_HPP_INCLUDED
