// SPDX-License-Identifier: MIT
#pragma once
#ifndef TIME_SHIELD_HEADER_TIME_SHIELD_ZONEDCLOCK_HPP_INCLUDED
#define TIME_SHIELD_HEADER_TIME_SHIELD_ZONEDCLOCK_HPP_INCLUDED

#include <time_shield/timezone/ZonedClock.hpp>

#endif // TIME_SHIELD_HEADER_TIME_SHIELD_ZONEDCLOCK_HPP_INCLUDED
