cmake_policy(VERSION 3.15)

if(NOT DEFINED TIME_SHIELD_SOURCE_DIR)
    message(FATAL_ERROR "TIME_SHIELD_SOURCE_DIR is required")
endif()

set(TIME_SHIELD_INCLUDE_DIR "${TIME_SHIELD_SOURCE_DIR}/include/time_shield")
set(TIME_SHIELD_DOMAIN_UMBRELLAS
    core.hpp conversions.hpp text.hpp date_time.hpp astronomy.hpp timers.hpp ntp.hpp timezone.hpp)

set(TIME_SHIELD_DOMAIN_DEPENDENCIES_core "")
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_conversions core)
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_text core conversions)
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_datetime core conversions text)
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_astronomy core conversions)
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_timers core)
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_ntp core)
set(TIME_SHIELD_DOMAIN_DEPENDENCIES_timezone core conversions text datetime ntp)

file(GLOB_RECURSE TIME_SHIELD_CANONICAL_HEADERS
    "${TIME_SHIELD_INCLUDE_DIR}/*/*.hpp")

foreach(header IN LISTS TIME_SHIELD_CANONICAL_HEADERS)
    file(RELATIVE_PATH relative_header "${TIME_SHIELD_INCLUDE_DIR}" "${header}")
    string(REPLACE "\\" "/" relative_header "${relative_header}")
    string(REGEX MATCH "^([^/]+)/" domain_match "${relative_header}")
    set(source_domain "${CMAKE_MATCH_1}")

    if(source_domain STREQUAL "detail" OR source_domain STREQUAL "ntp_client")
        continue()
    endif()
    if(relative_header MATCHES "(^|/)legacy_aliases\\.hpp$")
        continue()
    endif()

    file(STRINGS "${header}" header_lines)
    foreach(line IN LISTS header_lines)
        if(line MATCHES "#include[ \\t]+[\"<][^\">]*\\.\\./")
            message(FATAL_ERROR "Parent include is forbidden: ${relative_header}: ${line}")
        endif()

        if(line MATCHES "#include[ \\t]+<time_shield/([^>]+)>")
            set(target "${CMAKE_MATCH_1}")
            set(target_domain "")
            if(target STREQUAL "date_time.hpp")
                set(target_domain datetime)
            elseif(target IN_LIST TIME_SHIELD_DOMAIN_UMBRELLAS)
                string(REGEX REPLACE "\\.hpp$" "" target_domain "${target}")
            elseif(target MATCHES "^([^/]+)/")
                set(target_domain "${CMAKE_MATCH_1}")
            endif()

            if(target_domain)
                if(target MATCHES "/" AND NOT target_domain STREQUAL source_domain)
                    message(FATAL_ERROR
                        "Cross-domain leaf include is forbidden: ${relative_header}: ${line}")
                endif()
                if(target MATCHES "^[^/]+\\.hpp$" AND target_domain STREQUAL source_domain)
                    message(FATAL_ERROR
                        "Domain leaf must not include its own umbrella: ${relative_header}: ${line}")
                endif()
                set(allowed FALSE)
                set(allowed_domains "${TIME_SHIELD_DOMAIN_DEPENDENCIES_${source_domain}}")
                if(target_domain STREQUAL source_domain OR target_domain IN_LIST allowed_domains)
                    set(allowed TRUE)
                endif()
                if(NOT allowed)
                    message(FATAL_ERROR
                        "Forbidden domain dependency ${source_domain} -> ${target_domain}: ${relative_header}: ${line}")
                endif()
            endif()
        elseif(line MATCHES "#include[ \\t]+\"([^\"]+)\"")
            set(local_target "${CMAKE_MATCH_1}")
            if(local_target MATCHES "^\\.\\./")
                message(FATAL_ERROR "Parent include is forbidden: ${relative_header}: ${line}")
            endif()
            if(local_target MATCHES "/" AND NOT local_target MATCHES "^detail/" AND NOT local_target MATCHES "^ntp/")
                message(FATAL_ERROR "Nested cross-domain local include: ${relative_header}: ${line}")
            endif()
        endif()
    endforeach()
endforeach()

foreach(umbrella IN LISTS TIME_SHIELD_DOMAIN_UMBRELLAS)
    if(umbrella STREQUAL "date_time.hpp")
        set(source_domain datetime)
    else()
        string(REGEX REPLACE "\\.hpp$" "" source_domain "${umbrella}")
    endif()
    file(STRINGS "${TIME_SHIELD_INCLUDE_DIR}/${umbrella}" header_lines)
    foreach(line IN LISTS header_lines)
        if(line MATCHES "#include[ \\t]+<time_shield/([^>]+)>")
            set(target "${CMAKE_MATCH_1}")
            if(target STREQUAL "date_time.hpp")
                set(target_domain datetime)
            elseif(target IN_LIST TIME_SHIELD_DOMAIN_UMBRELLAS)
                string(REGEX REPLACE "\\.hpp$" "" target_domain "${target}")
            elseif(target MATCHES "^([^/]+)/")
                set(target_domain "${CMAKE_MATCH_1}")
            else()
                set(target_domain "")
            endif()
            if(target_domain)
                if(target MATCHES "/" AND NOT target_domain STREQUAL source_domain)
                    message(FATAL_ERROR
                        "Umbrella must include domain umbrellas, not leaves: ${umbrella}: ${line}")
                endif()
                set(allowed_domains "${TIME_SHIELD_DOMAIN_DEPENDENCIES_${source_domain}}")
                if(NOT target_domain STREQUAL source_domain AND NOT target_domain IN_LIST allowed_domains)
                    message(FATAL_ERROR
                        "Forbidden umbrella dependency ${source_domain} -> ${target_domain}: ${umbrella}: ${line}")
                endif()
            endif()
        endif()
    endforeach()
endforeach()

message(STATUS "Header include policy passed")
